rhboot/efivar

- src/linux.c
The kernel uses space as separators, whereas for some reason I'd coded
the parser to expect dashes.
Signed-off-by: Peter Jones <pjones@redhat.com>
> linux: Fix NVMe EUI parsing from sysfs

- src/dp-message.c
Signed-off-by: Peter Jones <pjones@redhat.com>
> _format_message_dn(): fix the check for a label in the EFIDP_MSG_VENDOR case.

- docs/efi_variable_t.3
Regarding issue #92, I believe that the man page contains a small error with regards to the `efi_variable_import()` and `efi_variable_export()` documentation. This can be resolved with a quick adjustment of the man page content.
> Minor correction to the efi_variable_import and efi_variable_export man page

- src/makeguids.c
initialize memory in makeguids
so that we do not write uninitialized memory into guids.bin and names.bin
which made the resulting libefivar.so.1.36 unreproducible.
See https://reproducible-builds.org/ for why this matters.
For background information on how ASLR triggers unreproducibility see https://github.com/bmwiedemann/theunreproduciblepackage/tree/master/aslr
> makeguids: initialize memory

- src/dp-message.c
- src/include/efivar/efivar-dp.h
- src/libefivar.map.in
- src/linux-emmc.c
- src/linux.c
- src/linux.h
Add emmc block device parser. The device string is like this:
mmc_host/mmc0/mmc0:0001/block/mmcblk0/mmcblk0p1
Without this patch, the emmc boot device cannot work with efi boot manager.
Signed-off-by: Alek Du <alek.du@intel.com>
> emmc_parser: add emmc_parser

- .gitignore
- src/dp-acpi.c
- src/error.c
- src/include/defaults.mk
- src/linux-acpi-root.c
- src/linux-acpi.c
- src/linux-ata.c
- src/linux-emmc.c
- src/linux-i2o.c
- src/linux-md.c
- src/linux-nvme.c
- src/linux-pci-root.c
- src/linux-pci.c
- src/linux-pmem.c
- src/linux-sas.c
- src/linux-sata.c
- src/linux-scsi.c
- src/linux-soc-root.c
- src/linux-virtblk.c
- src/linux-virtual-root.c
- src/linux.c
- src/linux.h
- src/util.h
This fixes some minor bugs, adds some debug logging to the parsers, and adds support for devices that show up in /sys/device/virtual/nvme-subsystem/ and /sys/device/virtual/nvme-fabrics/ .
> Handle /sys/devices/virtual/{nvme-fabrics,nvme-subsystem} devices

- src/guids.S
Intel Control-flow Enforcement Technology (CET):
https://software.intel.com/en-us/articles/intel-sdm
contains shadow stack (SHSTK) and indirect branch tracking (IBT). When
CET is enabled, ELF object files must be marked with .note.gnu.property
section. CET enabled GCC provides a header file, <cet.h>, which can be
included in assembly files to generate the CET marker automatically.
This fixes: https://github.com/rhboot/efivar/issues/148
Signed-off-by: H.J. Lu <hjl.tools@gmail.com>
> guids.S: Include <cet.h> when CET is enabled

- src/linux-emmc.c
Commit 471869409464 ("sysfs parsers: make all the /sys/block link
parsers work the same way") has broken sysfs parsing for eMMC-s when
the passed in path points to the whole block device.
In that case pos2 will stay at its -1 initializaton value, because we
only do 4 conversions; and when we then do:
current += pos2
We end up moving current one char position backwards and we end up
returning -1.
The correct position to use is always pos1 independent if we got
passed the whole disk; or a partition, as we always want to return
only the part which points to whole disk which ends at pos1.
Note that it seems that before commit 471869409464, the case where
path points to the partition was likely broken as the old code then
would return the entire path including the partition element.
Also see: …
> Fix /sys/block sysfs parsing for eMMC-s

- src/efivar.c
The return value check is wrong.
It expects mmap() to return zero on errors, however mmap() returns MAP_FAILED (or -1) when an error occurs.
> Properly check mmap return error

- src/lib.c
Add the check of NULL set_variable() to avoid segfault in a non-EFI
system.
Signed-off-by: Gary Lin <glin@suse.com>
> Handle NULL set_variable()

- src/linux-nvme.c
nvme-subsystem devices have a link that looks like:
../../devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1
However, the current code expects an additional /nvme0/ component, i.e.:
../../devices/virtual/nvme-subsystem/nvme-subsys0/nvme0/nvme0n1
Fix this by adding a separate branch for parsing nvme-subsystem devices.
Resolves github issue #157.
Signed-off-by: dann frazier <dann.frazier@canonical.com>
> Fix parsing for nvme-subsystem devices

- .gitignore
- src/.gitignore
- src/Makefile
- src/efivarfs.c
- src/error.c
- src/thread-test.c
- tests/Makefile
- tests/test-threading
In https://github.com/rhboot/efivar/issues/154 , @marler8997 noticed we have some thread safety bugs (though I *think* one of them was actually a getenv() usage bug).  This PR attempts to resolve those that were identified.
I don't have a particularly good way to test this, nor to actually detect thread safety bugs, so any help would be handy.
> Attempt to fix the identified thread safety bugs

- src/Makefile
Fix "make -j8" build failure by making thread-test depend on libefivar.so
instead of thread-test.o.  There is no need to make thread-test depend
on thread-test.o since thread-test is created from thread-test.c by
default.
Signed-off-by: H.J. Lu <hjl.tools@gmail.com>
> Make thread-test depend on libefivar.so

- src/libefiboot.abixml
- src/libefivar.abixml
Currently, we carry this fix downstream:
```
Fix abidw output for missing variadic arguments
GCC forgets to add the varidic arguments into debugging data if the
compilation unit is built with -flto option. As a result, the prebuilt
XML ABI dumps were missing the last argument at 4 functions (e.g.
efi_error_set()).
This was unnoticed until Fedora enabled LTO globally and had to
disable LTO in efivar explicitly because efivar uses symbol versioning
with top-level assembler statements which is not compatible with LTO.
Since then the abicheck failed:
make[2]: Leaving directory '/builddir/build/BUILD/efivar-37/src'
abidiff \
--suppr abignore \
--headers-dir2 /builddir/build/BUILD/efivar-37/src/include/efivar/ \
libefivar.abixml \
libefivar.so
Functions changes summary: 0 Removed, 2 Changed (8 …
```
> Upstream a local patch from rawhide

- .gitignore
- Makefile
- docs/Makefile
- efivar.spec.in
- src/Makefile
- src/guid.c
- src/guid.h
- src/include/defaults.mk
- src/include/deps.mk
- src/include/rules.mk
- src/libefiboot.abixml
- src/libefivar.abixml
- src/libefivar.map.in
- src/makeguids.c
Here are a bunch of relatively minor fixes.
> Misc minor fixes

- src/Makefile
- src/compiler.h
- src/efivar.h
- src/export.c
- src/include/efivar/efivar-time.h
- src/include/efivar/efivar-types.h
- src/include/efivar/efivar.h
- src/lib.h
- src/libefiboot.abixml
- src/libefivar.abixml
- src/libefivar.map.in
- src/list.h
- src/safemath.h
- src/time.c
- src/util.h
Note that this is layered on top of https://github.com/rhboot/efivar/pull/182
> Add efi_time_t declarations and helper functions.

- .github/workflows/ci.yml
- src/compiler.h
- src/lib.c
This makes the CI hook run "make test" as well as building the image,
and builds on more versions of fedora and centos.
Note that this is stacked on top of #185 
Signed-off-by: Peter Jones <pjones@redhat.com>
> Run CI on more targets

- src/dp-message.c
- src/efivar.h
- src/fix_coverity.h
- src/linux.c
- src/list.h
- src/makeguids.c
- src/thread-test.c
- src/time.c
This is a pile of minor fixes for stuff coverity and scan-build found that aren't related to PR 184.
> Coverity fixes 20211208

- .github/workflows/ci.yml
- src/abignore
Signed-off-by: Robbie Harwood <rharwood@redhat.com>
> CI: run abicheck

- src/linux-virtual-root.c
When some Samsung NVMe devices have mutlipath mode enabled, that
switches which kind of NVMe device shows up in sysfs, and we get a
path link that's like
"../../devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1".  The first
part of that, "../../devices/virtual/nvme-subsystem/", is supposed to be
consumed by the parser in linux-virtual-root.c.  Unfortunately, that
parse loop incorrectly expects that sscanf will return nonzero when it
parses the format string "%n../../devices/virtual/%n", but libc does not
consider %n to be a conversion, and does not count it.  In the log, we
see it find the string and set pos, but rc is 0, and "current" is not
advanced:
linux-virtual-root.c:47 parse_virtual_root(): searching for ../../devices/virtual
linux-virtual-root.c:50 parse_virtual_root(): …
> Fix linux virtual root device parsing

- src/include/workarounds.mk
Calling out to shell results in /bin/sh, so using a Bash-ism there won't
necesssarily work.  In particular, this breaks on Debian.
Suggested-by: Martin Haaß <vvvrrooomm@gmail.com>
Resolves: #193
Signed-off-by: Robbie Harwood <rharwood@redhat.com>
> Fix linker string comparison for dash

- src/include/efivar/efiboot-creator.h
- src/include/efivar/efiboot-loadopt.h
- src/include/efivar/efiboot.h
- src/include/efivar/efisec-secdb.h
- src/include/efivar/efisec-types.h
- src/include/efivar/efisec.h
- src/include/efivar/efivar-dp.h
- src/include/efivar/efivar-time.h
- src/include/efivar/efivar-types.h
- src/include/efivar/efivar.h
- src/makeguids.c
Add `extern "C"` directly to all headers except efivar-guids.h, which
is generated. Because it interferes with C compilers, wrap each
`extern` in an `#ifdef __cplusplus`. For efivar-guids.h update the
generator, makeguids.c, to add the desired code.
From https://en.cppreference.com/w/cpp/language/language_linkage:
> extern "C" makes it possible to include header files containing
> declarations of C library functions in a C++ program, but if the
> same header file is shared with a C program, extern "C" (which
> is not allowed in C) must be hidden with an appropriate #ifdef,
> typically __cplusplus.
fixes #205 
Tests:
* `make` and `make test` both work
* tested in my project with `extern "C"` removed from my code.
> Add `extern "C"` to headers for easier use by C++

- src/esl-iter.c
- src/secdb-dump.c
Follow up to https://github.com/rhboot/efivar/issues/209
---
On i686 definition of off_t and ssize_t differ.  Update format length
modifiers as needed to avoid format errors with GCC.
> Avoid format error on i686

- src/include/defaults.mk
There is an issue on riscv64 system when compiling it natively:
gcc: error: '-march=native': ISA string must begin with rv32 or rv64
This patch set HOST_MARCH= like ia64 to resolve the issue.
Signed-off-by: Wei Fu <wefu@redhat.com>
> Fix the -march issue for riscv64

- src/compiler.h
- src/efisecdb.c
Fix build with musl by using POSTIX atexit(3) instead of GNU specific on_exit(3).
Also fix potential double free in error handling while at it.
Fixes https://github.com/rhboot/efivar/issues/197
Fixes https://github.com/rhboot/efivar/issues/202
> Fix musl build

- src/efivar.c
data is allocated by mmap() in prepare_data().
Resolves: #173
Signed-off-by: Robbie Harwood <rharwood@redhat.com>
> Fix invalid free in main()

- src/include/defaults.mk
- src/include/gcc.specs
Resolves #204 
The --add-needed linker flag is not supported by the LLD and Gold linkers, and moreover from what I can tell it doesn't actually serve much of a purpose.
I compiled efivar on Gentoo with --add-needed and with a patch to remove it, and the checksums of the resulting libraries were the same.
If there's any reason that I'm missing for keeping this flag in, please let me know.
Unfortunately this patch still doesn't allow for efivar to be compiled with Clang + LLD, as we get a new error: ```ld.lld: error: unable to insert .data after .data```
> Remove deprecated --add-needed linker flag

- src/Makefile
util.c needs to be built twice when cross-compiling:
for the build machine to be able to link with
makeguids which then runs during the same build,
and then for the actual target.
Signed-off-by: Alexander Kanavin <alex@linutronix.de>
> src/Makefile: build util.c separately for makeguids

- src/include/workarounds.mk
If the user has a different locale set, ld --version may not contain the
string "GNU ld".
For example, in Italian, ld --version outputs "ld di GNU".
Signed-off-by: Mike Gilbert <floppym@gentoo.org>
> Set LC_ALL=C to force English output from ld

- src/include/workarounds.mk
Hi,
This PR fixes:
https://github.com/rhboot/efivar/issues/220
https://github.com/rhboot/efivar/issues/219
> LLD: fix detection and remove not needed workarounds

- src/gpt.c
- src/linux.c
- src/util.h
glibc has decided that sys/mount.h and linux/mount.h are no longer
usable at the same time.  This broke the build, since linux/fs.h itself
includes linux/mount.h.  For now, fix the build by only including
sys/mount.h where we need it.
See-also: https://sourceware.org/glibc/wiki/Release/2.36#Usage_of_.3Clinux.2Fmount.h.3E_and_.3Csys.2Fmount.h.3E
Resolves: #227
Signed-off-by: Robbie Harwood <rharwood@redhat.com>
> Fix glibc 2.36 build (mount.h conflicts)

- src/dp-media.c
- src/dp-message.c
- src/include/efivar/efivar-dp.h
ardb poked me about a few efivar device path issues:
- File device paths are printed wrong
- IPv4 device paths are printed wrong
- IPv6 device paths are printed wrong
> File device paths: don't print "File(" or ")"

- src/error.c
- src/include/defaults.mk
Pass _FILE_OFFSET_BITS=64 to ensure 64bit off_t
Signed-off-by: Khem Raj <raj.khem@gmail.com>
> Use off_t instead of off64_t

- src/include/defaults.mk
In my ChromiumOS build calling pkg-config without an appropriate cross-compilation prefix is considered an error. The current method of detecting PKG_CONFIG in efivar _always_ calls pkg-config, even if PKG_CONFIG has already been set in the environment.
Allow overriding PKG_CONFIG, rather than always checking for the cross-compiled version. This is more in-line with how the other tools are chosen.
Signed-off-by: Ted Brandston <tbrandston@google.com>
> Allow overriding PKG_CONFIG

- src/efivar.c
It's a bitmask of flags, it's much nicer to reason about it using hex
> Allow passing of hex values to -A

- src/efivar.c
There is no much point in failing when trying to append, we may as well create the variable. This way it can be used for dbx update payloads that must be applied in append mode even if there isn't a dbx yet.
This is nicer than using -w with EFI_VARIABLE_APPEND_WRITE added to the attributes passed with -A
> Allow -a to create a non-existent variable

- Makefile
- src/include/defaults.mk
`ENABLE_DOCS=0 make` will remove the docs subdirectory from the list of targets. This is useful if the target OS does not ship manpages and so the builder doesn't have `mandoc`.
> make: add option to disable building/installing the docs

- src/esl-iter.h
Upcoming `gcc-13` detected return type mismatch as:
esl-iter.c:84:1: error: conflicting types for 'esl_iter_next_with_size_correction' due to enum/integer mismatch; have 'esl_iter_status_t(esl_iter *, efi_guid_t *, efi_guid_t *, uint8_t **, size_t *, _Bool)' {aka 'enum esl_iter_status(esl_iter *, efi_guid_t *, efi_guid_t *, unsigned char **, long unsigned int *, _Bool)'} [-Werror=enum-int-mismatch]
84 | esl_iter_next_with_size_correction(esl_iter *iter, efi_guid_t *type,
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from efisec.h:25,
from esl-iter.c:7:
esl-iter.h:61:12: note: previous declaration of 'esl_iter_next_with_size_correction' with type 'int(esl_iter *, efi
*, efi_guid_t *, uint8_t **, size_t *, _Bool)' {aka 'int(esl_iter *, efi_guid_t *, efi_guid_t *, unsigned char **, …
> esl-iter.h: fix type declaration of return value for gcc-13

- src/creator.c
- src/disk.c
- src/export.c
- src/gpt.c
- src/guid.h
- src/include/efivar/efiboot.h
- src/include/efivar/efivar.h
- src/lib.h
- src/util.h
While making this project work on BSD systems (in limited capacity) I stumbled upon some things in the code which you might want to fix.  Of course, there were more changes related to compatibility, but given that the project is targeting Linux I've skipped them and submitting only those which make sense to apply in general.
> Minor code updates

- src/linux.c
/sys/devices/pci0000:00/firmware_node/hid does not exist on all systems. Kernel parameter acpi=off has been reported as one possible reason in https://github.com/rhboot/efivar/issues/120
But this is not the only case. On systems using device trees you may also not find this file.
We have multiple parsers in dev_probes[]. It is sufficient that one of these parsers succeeds to provide the device information.
If for instance pci_root_parser and pci_parser fails, we may still get information from nvme_parser.
If a parser fails, only write a debug information and continue.
> linux: handle non-ACPI systems in device_get()

- src/efivarfs.c
- src/generics.h
- src/include/efivar/efivar.h
- src/lib.c
- src/lib.h
- src/vars.c
All implementations of set_variable and append_variable never modify the data pointed to. Callers don't know by the function signitures that their data will not be modified nor can they pass const buffers without warnings. This commit adds const to all function signatures and fixes the one assignment where the pointer is copied to a non-const pointer.
> Change set&append data to be const.

- src/dp.h
When memcpy() is called in format_ucs2(), the value of ucs2size - sizeof(uint16_t) is not checked. It may result in out-of-bounds writing due to integer underflow.
> dp.h: check _ucs2size in format_ucs2()

- src/export.c
The wrong if condition in efi_variable_get_data result in empty value of printing variable from --import. Fix #254
> Fix wrong if condition in efi_variable_get_data

- README.md
All of the source files are tagged LGPL-2.1-or-later. Make the README license statement reflect that.
Fixes #215
> Make README statement match license

- src/efivarfs.c
The access() is always validated(!?) by a statfs(): there's no need for this, but this incurs an additional syscall
git show -w:
```diff
diff --git a/src/efivarfs.c b/src/efivarfs.c
index d4cee45..fe7ba9e 100644
--- a/src/efivarfs.c
+++ b/src/efivarfs.c
@@ -69,7 +69,6 @@ efivarfs_probe(void)
{
const char *path = get_efivarfs_path();
-       if (!access(path, F_OK)) {
int rc = 0;
struct statfs buf;
@@ -91,9 +90,6 @@ efivarfs_probe(void)
} else {
efi_error("statfs(%s) failed", path);
}
-       } else {
-               efi_error("access(%s, F_OK) failed", path);
-       }
return 0;
}
```
> Remove needless access() in efivarfs_probe()

- src/creator.c
- src/dp-acpi.c
- src/dp-hw.c
- src/dp-media.c
- src/dp-message.c
- src/dp.c
- src/dp.h
- src/safemath.h
One of our internal analyzers noticed some issues in our usage of `efidp_node_size()` in the device path formatters.  This patch attempts to address those issues.
> Fix incorrect error handling in callers of `efidp_node_size()`

- docs/efi_get_variable.3
Documentation for efi_get_variable doesn't say that it is the caller's responsibility to free the 'data' pointer.
For issue:
https://github.com/rhboot/efivar/issues/277
> Add note to efi_get_variable about ownership of the data pointer

- src/efivarfs.c
Embedded boards have hardware limitations when storing and managing EFI variables. Some hardware comes with an eMMC & an RPMB partition which they use to store the EFI variables securely. However, the vast majority of boards (using U-Boot), stores the EFI variables in a file in the ESP.
This has a few limitations
- UEFI secure boot cannot be enabled as it can be very easily overridden
- SetVariable at runtime is impossible to support
Distros and capsule updates on-disk do rely on the that service though and U-Boot does implement a workaround.
U-Boot enables SetVariableRT in the RTPROP table and creates a memory backend, so the linux kernel can naturally read and write variables via the efivarfs filesystem. Those reads and writes end up in memory though. So they are visible while the OS is …
> efivarfs: Update a file variable store On SetVariable RT
